<a href="https://colab.research.google.com/github/aliyah06667/Praktikum-AVD_Mini-Project/blob/main/Checkpoint_2_Aliyah_Azzah_Sekedang_021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **E-commerce Customer Behavior Dataset**

Link Kaggle

---



(https://www.kaggle.com/datasets/uom190346a/e-commerce-customer-behavior-dataset)

## **Data Understanding**

### 1. Membaca Data

In [2]:
import pandas as pd

In [3]:
file_path = "E-commerce Customer Behavior - Sheet1.csv"

df = pd.read_csv(file_path)
df

# df = pd.read_excel(file_path)
# df

,Customer ID,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount Applied,Days Since Last Purchase,Satisfaction Level
0,101,Female,29,New York,Gold,1120.20,14,4.6,True,25,Satisfied
1,102,Male,34,Los Angeles,Silver,780.50,11,4.1,False,18,Neutral
2,103,Female,43,Chicago,Bronze,510.75,9,3.4,True,42,Unsatisfied
3,104,Male,30,San Francisco,Gold,1480.30,19,4.7,False,12,Satisfied
4,105,Male,27,Miami,Silver,720.40,13,4.0,True,55,Unsatisfied
...,...,...,...,...,...,...,...,...,...,...,...
345,446,Male,32,Miami,Silver,660.30,10,3.8,True,42,Unsatisfied
346,447,Female,36,Houston,Bronze,470.50,8,3.0,False,27,Neutral
347,448,Female,30,New York,Gold,1190.80,16,4.5,True,28,Satisfied
348,449,Male,34,Los Angeles,Silver,780.20,11,4.2,False,21,Neutral
349,450,Female,43,Chicago,Bronze,515.75,10,3.3,True,49,Unsatisfied

### 2. Pengecekan Struktur Data

1. Pemeriksaan terhadap struktur data
2. Tipe data pada setiap kolom
3. Jumlah baris dan kolom yang terdapat dalam dataset

In [4]:
kolom_tertentu = "Produk"
if kolom_tertentu in df.columns:
    print(f"\nMenghitung jumlah kemunculan nilai unik dalam kolom '{kolom_tertentu}' dengan df['{kolom_tertentu}'].value_counts():")
    print(df[kolom_tertentu].value_counts())
else:
    print(f"\nKolom '{kolom_tertentu}' tidak ditemukan dalam dataset.")

print("\nMenghitung rata-rata dengan df.mean():")
print(df.mean(numeric_only=True))

print("\nMenghitung median dengan df.median():")
print(df.median(numeric_only=True))

print("\nMenghitung standar deviasi dengan df.std():")
print(df.std(numeric_only=True))

Kolom 'Produk' tidak ditemukan dalam dataset.

Menghitung rata-rata dengan df.mean():
Customer ID                 275.500000
Age                          33.597143
Total Spend                 845.381714
Items Purchased              12.600000
Average Rating                4.019143
Discount Applied              0.500000
Days Since Last Purchase     26.588571
dtype: float64

Menghitung median dengan df.median():
Customer ID                 275.5
Age                          32.5
Total Spend                 775.2
Items Purchased              12.0
Average Rating                4.1
Discount Applied              0.5
Days Since Last Purchase     23.0
dtype: float64

Menghitung standar deviasi dengan df.std():
Customer ID                 101.180532
Age                           4.870882
Total Spend                 362.058695
Items Purchased               4.155984
Average Rating                0.580539
Discount Applied              0.500716
Days Since Last Purchase     13.440813
dtype: float64

In [5]:
print("\nMenampilkan ringkasan informasi dataset dengan df.info():")
df.info()

Menampilkan ringkasan informasi dataset dengan df.info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               350 non-null    int64
 1   Gender                    350 non-null    object
 2   Age                       350 non-null    int64
 3   City                      350 non-null    object
 4   Membership Type           350 non-null    object
 5   Total Spend               350 non-null    float64
 6   Items Purchased           350 non-null    int64
 7   Average Rating            350 non-null    float64
 8   Discount Applied          350 non-null    bool
 9   Days Since Last Purchase  350 non-null    int64
 10  Satisfaction Level        348 non-null    object
dtypes: bool(1), float64(2), int64(4), object(4)
memory usage: 27.8+ KB

In [6]:
print("\nMenampilkan tipe data setiap kolom dengan df.dtypes:")
df.dtypes

Menampilkan tipe data setiap kolom dengan df.dtypes:

Customer ID                   int64
Gender                       object
Age                           int64
City                         object
Membership Type              object
Total Spend                 float64
Items Purchased               int64
Average Rating              float64
Discount Applied               bool
Days Since Last Purchase      int64
Satisfaction Level           object
dtype: object

In [7]:
print("\nMenampilkan jumlah baris dan kolom dengan df.shape:")
df.shape

Menampilkan jumlah baris dan kolom dengan df.shape:

(350, 11)

3. Statistik Deskriptif dan Analisis Korelasi

In [8]:
print("\nMenampilkan statistik deskriptif dengan df.describe():")
df.describe()

Menampilkan statistik deskriptif dengan df.describe():

,Customer ID,Age,Total Spend,Items Purchased,Average Rating,Days Since Last Purchase
count,350.000000,350.000000,350.000000,350.000000,350.000000,350.000000
mean,275.500000,33.597143,845.381714,12.600000,4.019143,26.588571
std,101.180532,4.870882,362.058695,4.155984,0.580539,13.440813
min,101.000000,26.000000,410.800000,7.000000,3.000000,9.000000
25%,188.250000,30.000000,502.000000,9.000000,3.500000,15.000000
50%,275.500000,32.500000,775.200000,12.000000,4.100000,23.000000
75%,362.750000,37.000000,1160.600000,15.000000,4.500000,38.000000
max,450.000000,43.000000,1520.100000,21.000000,4.900000,63.000000

In [9]:
print("\nMenghitung korelasi antar kolom numerik dengan df.corr():")
print(df.corr(numeric_only=True))

Menghitung korelasi antar kolom numerik dengan df.corr():
                          Customer ID       Age  Total Spend  Items Purchased  \
Customer ID                  1.000000  0.011171    -0.006316        -0.003230
Age                          0.011171  1.000000    -0.677918        -0.685274
Total Spend                 -0.006316 -0.677918     1.000000         0.972425
Items Purchased             -0.003230 -0.685274     0.972425         1.000000
Average Rating              -0.000510 -0.722277     0.941475         0.922028
Discount Applied            -0.000707  0.056979    -0.160723        -0.114285
Days Since Last Purchase     0.117940  0.168763    -0.540089        -0.420393

                          Average Rating  Discount Applied  \
Customer ID                    -0.000510         -0.000707
Age                            -0.722277          0.056979
Total Spend                     0.941475         -0.160723
Items Purchased                 0.922028         -0.114285
Average Rating                  1.000000         -0.068507
Discount Applied               -0.068507          1.000000
Days Since Last Purchase       -0.430757          0.759543

                          Days Since Last Purchase
Customer ID                               0.117940
Age                                       0.168763
Total Spend                              -0.540089
Items Purchased                          -0.420393
Average Rating                           -0.430757
Discount Applied                          0.759543
Days Since Last Purchase                  1.000000

## **Data Preparation**

### 1. Membaca Data

In [10]:
df = pd.read_csv("/content/E-commerce Customer Behavior - Sheet1.csv")

df

,Customer ID,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount Applied,Days Since Last Purchase,Satisfaction Level
0,101,Female,29,New York,Gold,1120.20,14,4.6,True,25,Satisfied
1,102,Male,34,Los Angeles,Silver,780.50,11,4.1,False,18,Neutral
2,103,Female,43,Chicago,Bronze,510.75,9,3.4,True,42,Unsatisfied
3,104,Male,30,San Francisco,Gold,1480.30,19,4.7,False,12,Satisfied
4,105,Male,27,Miami,Silver,720.40,13,4.0,True,55,Unsatisfied
...,...,...,...,...,...,...,...,...,...,...,...
345,446,Male,32,Miami,Silver,660.30,10,3.8,True,42,Unsatisfied
346,447,Female,36,Houston,Bronze,470.50,8,3.0,False,27,Neutral
347,448,Female,30,New York,Gold,1190.80,16,4.5,True,28,Satisfied
348,449,Male,34,Los Angeles,Silver,780.20,11,4.2,False,21,Neutral
349,450,Female,43,Chicago,Bronze,515.75,10,3.3,True,49,Unsatisfied

### 2. Pengecekan Data

#### **Missing Values**

In [11]:
print((df.isna().sum() / len(df)) * 100)

Customer ID                 0.000000
Gender                      0.000000
Age                         0.000000
City                        0.000000
Membership Type             0.000000
Total Spend                 0.000000
Items Purchased             0.000000
Average Rating              0.000000
Discount Applied            0.000000
Days Since Last Purchase    0.000000
Satisfaction Level          0.571429
dtype: float64

Melakukan pengecekan nilai kosong pada kolom Satisfaction Level

In [12]:
df[df['Satisfaction Level'].isnull()]

,Customer ID,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount Applied,Days Since Last Purchase,Satisfaction Level
71,172,Female,37,Houston,Bronze,420.8,7,3.1,False,21,NaN
143,244,Female,37,Houston,Bronze,430.8,7,3.4,False,23,NaN

Melakukan imputasi

In [13]:
df['Satisfaction Level'].dropna().describe()

count           348
unique            3
top       Satisfied
freq            125
Name: Satisfaction Level, dtype: object

In [14]:
df['Satisfaction Level'] = df['Satisfaction Level'].fillna(df['Satisfaction Level'].mode()[0])

In [15]:
df

,Customer ID,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount Applied,Days Since Last Purchase,Satisfaction Level
0,101,Female,29,New York,Gold,1120.20,14,4.6,True,25,Satisfied
1,102,Male,34,Los Angeles,Silver,780.50,11,4.1,False,18,Neutral
2,103,Female,43,Chicago,Bronze,510.75,9,3.4,True,42,Unsatisfied
3,104,Male,30,San Francisco,Gold,1480.30,19,4.7,False,12,Satisfied
4,105,Male,27,Miami,Silver,720.40,13,4.0,True,55,Unsatisfied
...,...,...,...,...,...,...,...,...,...,...,...
345,446,Male,32,Miami,Silver,660.30,10,3.8,True,42,Unsatisfied
346,447,Female,36,Houston,Bronze,470.50,8,3.0,False,27,Neutral
347,448,Female,30,New York,Gold,1190.80,16,4.5,True,28,Satisfied
348,449,Male,34,Los Angeles,Silver,780.20,11,4.2,False,21,Neutral
349,450,Female,43,Chicago,Bronze,515.75,10,3.3,True,49,Unsatisfied

#### **Duplikat**

In [16]:
df[df.duplicated()]

Empty DataFrame
Columns: [Customer ID, Gender, Age, City, Membership Type, Total Spend, Items Purchased, Average Rating, Discount Applied, Days Since Last Purchase, Satisfaction Level]
Index: []

In [17]:
df = df.drop_duplicates()

In [18]:
df

,Customer ID,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount Applied,Days Since Last Purchase,Satisfaction Level
0,101,Female,29,New York,Gold,1120.20,14,4.6,True,25,Satisfied
1,102,Male,34,Los Angeles,Silver,780.50,11,4.1,False,18,Neutral
2,103,Female,43,Chicago,Bronze,510.75,9,3.4,True,42,Unsatisfied
3,104,Male,30,San Francisco,Gold,1480.30,19,4.7,False,12,Satisfied
4,105,Male,27,Miami,Silver,720.40,13,4.0,True,55,Unsatisfied
...,...,...,...,...,...,...,...,...,...,...,...
345,446,Male,32,Miami,Silver,660.30,10,3.8,True,42,Unsatisfied
346,447,Female,36,Houston,Bronze,470.50,8,3.0,False,27,Neutral
347,448,Female,30,New York,Gold,1190.80,16,4.5,True,28,Satisfied
348,449,Male,34,Los Angeles,Silver,780.20,11,4.2,False,21,Neutral
349,450,Female,43,Chicago,Bronze,515.75,10,3.3,True,49,Unsatisfied

#### **Outliers**

In [19]:
results = []

cols = df.select_dtypes(include=['float64', 'int64'])

for col in cols:
  q1 = df[col].quantile(0.25)
  q3 = df[col].quantile(0.75)
  iqr = q3 - q1
  lower_bound = q1 - 1.5*iqr
  upper_bound = q3 + 1.5*iqr
  outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
  percent_outliers = (len(outliers)/len(df))*100
  results.append({'Kolom': col, 'Persentase Outliers': percent_outliers})

# Dataframe dari list hasil
results_df = pd.DataFrame(results)
results_df.set_index('Kolom', inplace=True)
results_df = results_df.rename_axis(None, axis=0).rename_axis('Kolom', axis=1)

# Tampilkan dataframe
display(results_df)

Kolom                     Persentase Outliers
Customer ID                               0.0
Age                                       0.0
Total Spend                               0.0
Items Purchased                           0.0
Average Rating                            0.0
Days Since Last Purchase                  0.0

In [20]:
df

,Customer ID,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount Applied,Days Since Last Purchase,Satisfaction Level
0,101,Female,29,New York,Gold,1120.20,14,4.6,True,25,Satisfied
1,102,Male,34,Los Angeles,Silver,780.50,11,4.1,False,18,Neutral
2,103,Female,43,Chicago,Bronze,510.75,9,3.4,True,42,Unsatisfied
3,104,Male,30,San Francisco,Gold,1480.30,19,4.7,False,12,Satisfied
4,105,Male,27,Miami,Silver,720.40,13,4.0,True,55,Unsatisfied
...,...,...,...,...,...,...,...,...,...,...,...
345,446,Male,32,Miami,Silver,660.30,10,3.8,True,42,Unsatisfied
346,447,Female,36,Houston,Bronze,470.50,8,3.0,False,27,Neutral
347,448,Female,30,New York,Gold,1190.80,16,4.5,True,28,Satisfied
348,449,Male,34,Los Angeles,Silver,780.20,11,4.2,False,21,Neutral
349,450,Female,43,Chicago,Bronze,515.75,10,3.3,True,49,Unsatisfied

Melakukan imputasi

In [21]:
columns_to_impute = ["Satisfaction Level"]

for col in columns_to_impute:
    mode_value = df[col].mode()[0]

    # Menggunakan .loc[] agar tidak muncul SettingWithCopyWarning
    df.loc[:, col] = df[col].fillna(mode_value)

Melakukan pengecekan ulang

In [22]:
df["Satisfaction Level"].value_counts()

Satisfaction Level
Satisfied      127
Unsatisfied    116
Neutral        107
Name: count, dtype: int64

In [23]:
df

,Customer ID,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount Applied,Days Since Last Purchase,Satisfaction Level
0,101,Female,29,New York,Gold,1120.20,14,4.6,True,25,Satisfied
1,102,Male,34,Los Angeles,Silver,780.50,11,4.1,False,18,Neutral
2,103,Female,43,Chicago,Bronze,510.75,9,3.4,True,42,Unsatisfied
3,104,Male,30,San Francisco,Gold,1480.30,19,4.7,False,12,Satisfied
4,105,Male,27,Miami,Silver,720.40,13,4.0,True,55,Unsatisfied
...,...,...,...,...,...,...,...,...,...,...,...
345,446,Male,32,Miami,Silver,660.30,10,3.8,True,42,Unsatisfied
346,447,Female,36,Houston,Bronze,470.50,8,3.0,False,27,Neutral
347,448,Female,30,New York,Gold,1190.80,16,4.5,True,28,Satisfied
348,449,Male,34,Los Angeles,Silver,780.20,11,4.2,False,21,Neutral
349,450,Female,43,Chicago,Bronze,515.75,10,3.3,True,49,Unsatisfied

#### **Incosistent Value**

In [33]:
kolom_kategorikal = [
    'Customer ID', 'Gender', 'Age', 'City', 'Membership Type',
    'Total Spend', 'Items Purchased', 'Average Rating', 'Discount Applied',
    'Days Since Last Purchase', 'Satisfaction Level'
]

for col in kolom_kategorikal:
    print(f"Kolom: {col}")
    print(df[col].value_counts())  # Cek nilai unik dalam kolom
    print("-" * 50)

Kolom: Customer ID
Customer ID
101    1
331    1
339    1
338    1
337    1
      ..
216    1
215    1
214    1
213    1
450    1
Name: count, Length: 350, dtype: int64
--------------------------------------------------
Kolom: Gender
Gender
Female    175
Male      175
Name: count, dtype: int64
--------------------------------------------------
Kolom: Age
Age
30    48
32    33
43    25
27    25
31    25
35    25
36    25
34    24
37    24
41    24
28    24
29    11
33    10
42     9
26     9
38     9
Name: count, dtype: int64
--------------------------------------------------
Kolom: City
City
New York         59
Los Angeles      59
Chicago          58
San Francisco    58
Miami            58
Houston          58
Name: count, dtype: int64
--------------------------------------------------
Kolom: Membership Type
Membership Type
Gold      117
Silver    117
Bronze    116
Name: count, dtype: int64
--------------------------------------------------
Kolom: Total Spend
Total Spend
710.40     15
505.75     12
470.50     12
430.80     12
820.90     12
           ..
530.40      1
1360.20     1
700.60      1
450.90      1
1120.20     1
Name: count, Length: 76, dtype: int64
--------------------------------------------------
Kolom: Items Purchased
Items Purchased
10    47
9     34
8     33
12    33
13    32
11    28
7     25
15    24
21    24
16    24
20    19
14    11
18     9
19     6
17     1
Name: count, dtype: int64
--------------------------------------------------
Kolom: Average Rating
Average Rating
4.1    34
4.5    31
3.3    25
3.8    24
4.9    24
3.6    24
4.7    22
4.8    21
4.3    20
3.4    19
4.0    18
3.1    17
4.2    12
3.0    12
4.6    11
3.2    10
3.5     9
4.4     8
3.9     8
3.7     1
Name: count, dtype: int64
--------------------------------------------------
Kolom: Discount Applied
Discount Applied
True     175
False    175
Name: count, dtype: int64
--------------------------------------------------
Kolom: Days Since Last Purchase
Days Since Last Purchase
13    20
12    17
10    17
19    16
39    16
14    13
18    12
23    11
22    11
15    11
24    11
20    11
21    10
17    10
27    10
9      9
38     9
47     9
40     9
26     9
32     9
37     8
33     8
54     8
25     6
11     6
28     6
53     5
16     5
41     4
42     4
46     3
35     3
34     3
48     3
29     3
55     2
45     2
30     2
36     2
43     2
31     2
44     2
63     1
62     1
61     1
60     1
56     1
59     1
58     1
57     1
52     1
50     1
49     1
Name: count, dtype: int64
--------------------------------------------------
Kolom: Satisfaction Level
Satisfaction Level
Satisfied      127
Unsatisfied    116
Neutral        107
Name: count, dtype: int64
--------------------------------------------------

In [45]:
df

,Customer ID,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount Applied,Days Since Last Purchase,Satisfaction Level
0,101,Female,29,new york,gold,1120.2,14,4.6,true,25,satisfied
1,102,Male,34,los angeles,silver,780.5,11,4.1,false,18,neutral
2,103,Female,43,chicago,bronze,510.75,9,3.4,true,42,unsatisfied
3,104,Male,30,san francisco,gold,1480.3,19,4.7,false,12,satisfied
4,105,Male,27,miami,silver,720.4,13,4.0,true,55,unsatisfied
...,...,...,...,...,...,...,...,...,...,...,...
345,446,Male,32,miami,silver,660.3,10,3.8,true,42,unsatisfied
346,447,Female,36,houston,bronze,470.5,8,3.0,false,27,neutral
347,448,Female,30,new york,gold,1190.8,16,4.5,true,28,satisfied
348,449,Male,34,los angeles,silver,780.2,11,4.2,false,21,neutral
349,450,Female,43,chicago,bronze,515.75,10,3.3,true,49,unsatisfied

#### **Construct Data**

In [52]:
df["Days Since Last Purchase"] = pd.to_numeric(df["Days Since Last Purchase"], errors="coerce")

df["Last Purchase Date"] = pd.Timestamp.today() - pd.to_timedelta(df["Days Since Last Purchase"], unit='D')

df["Day"] = df["Last Purchase Date"].dt.day_name()

df["Total Spend"] = pd.to_numeric(df["Total Spend"], errors="coerce")
df["Items Purchased"] = pd.to_numeric(df["Items Purchased"], errors="coerce")

df["Spend_per_Item"] = df["Total Spend"] / df["Items Purchased"]
df["Spend_per_Item"].fillna(0, inplace=True)

median_spend = df["Total Spend"].median()
df["High Value Customer"] = df["Total Spend"] > median_spend

df["Satisfied"] = df["Satisfaction Level"] == "Satisfied"

print(df.head())

  Customer ID  Gender Age           City Membership Type  Total Spend  \
0         101  Female  29       new york            gold      1120.20
1         102    Male  34    los angeles          silver       780.50
2         103  Female  43        chicago          bronze       510.75
3         104    Male  30  san francisco            gold      1480.30
4         105    Male  27          miami          silver       720.40

   Items Purchased Average Rating Discount Applied  Days Since Last Purchase  \
0               14            4.6             true                        25
1               11            4.1            false                        18
2                9            3.4             true                        42
3               19            4.7            false                        12
4               13            4.0             true                        55

  Satisfaction Level         Last Purchase Date        Day  Spend_per_Item  \
0          satisfied 2025-02-13 00:13:41.170977   Thursday       80.014286
1            neutral 2025-02-20 00:13:41.170977   Thursday       70.954545
2        unsatisfied 2025-01-27 00:13:41.170977     Monday       56.750000
3          satisfied 2025-02-26 00:13:41.170977  Wednesday       77.910526
4        unsatisfied 2025-01-14 00:13:41.170977    Tuesday       55.415385

   High Value Customer  Satisfied
0                 True      False
1                 True      False
2                False      False
3                 True      False
4                False      False

<ipython-input-52-de363c4290fc>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Spend_per_Item"].fillna(0, inplace=True)

#### **Data Reduction**

In [53]:
df.drop(columns=["Customer ID", "Last Purchase Date"], inplace=True)

df = df[df["Days Since Last Purchase"] <= 30]

df["Membership Category"] = df["Membership Type"].replace({
    "Gold": "Premium",
    "Silver": "Premium",
    "Bronze": "Regular"
})

print(df.head())

   Gender Age           City Membership Type  Total Spend  Items Purchased  \
0  Female  29       new york            gold       1120.2               14
1    Male  34    los angeles          silver        780.5               11
3    Male  30  san francisco            gold       1480.3               19
5  Female  37        houston          bronze        440.8                8
6  Female  31       new york            gold       1150.6               15

  Average Rating Discount Applied  Days Since Last Purchase  \
0            4.6             true                        25
1            4.1            false                        18
3            4.7            false                        12
5            3.1            false                        22
6            4.5             true                        28

  Satisfaction Level        Day  Spend_per_Item  High Value Customer  \
0          satisfied   Thursday       80.014286                 True
1            neutral   Thursday       70.954545                 True
3          satisfied  Wednesday       77.910526                 True
5            neutral     Sunday       55.100000                False
6          satisfied     Monday       76.706667                 True

   Satisfied Membership Category
0      False                gold
1      False              silver
3      False                gold
5      False              bronze
6      False                gold

<ipython-input-53-7c5166c5c66c>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Membership Category"] = df["Membership Type"].replace({